### ISSUE TITLE
How to deploy in production? -- Options and best pratices

### ISSUE THREAD

**Issue by keyscores** [mattkrick/meatier#67]
Really enjoying meatier. The production bundling makes a lot of sense. Though I'd like a tool like mupx (using docker) to deploy a production app. Any thought on hacking mupx for this?

**Comment by Bartekus** [comment]
We are currently working with azk.io in the area of common development environment and deployment. The whole process is nearly completed but few rough spots need to be ironed out before the release. However I'll look into mupx as well since it would be a shame to omit any potential great tool that could also make meatier a better build all together.

**Comment by keyscores** [comment]
Never heard of Azk.io, seems like it could work well. Good job I really like the meatier project...

**Comment by patrickleet** [comment]
@keyscores check out my PR here: https://github.com/mattkrick/meatier/pull/64

These were the changes that were required to deploy meatier on modulus.io using codeship as a CI/build server, and a Compose RethinkDB deployment.

Using this process, deploying is as simple as ```git push origin master```. 

All you need to do is go to codeship.com, select your repository with the github integration, and select modulus for the deployment integration.  You can use their command line tool to generate an API token. (haven't tried others but nodejitsu doesn't seem to be accepting new clients, and heroku runs the build on their side typically, and that isn't necessary with codeship handling it) 

For the test script you can use this:
```shell
# By default we use the Node.js version set in your package.json or the latest
# version from the 0.10 release
#
# You can use nvm to install any Node.js (or io.js) version you require.
# nvm install 4.0
nvm install 5.4.1
npm install
# we want to build the db for testing
NODE_ENV=testing npm run build:db
# build client and server with production settings (handled by npm tasks)
npm run build:client
npm run build:server
```

I actually started with the azk.io branch @Bartekus made when going down this route, but azk.io seemed to be pretty lacking in the deployment capabilities. For local development it is great, but I couldn't figure out how to just deploy one "system", and not the db for example. I'm looking forward to see what you can make of it @Bartekus.

**Comment by paralin** [comment]
I've just discovered meatier and azk. As a long time Meteor user and with a Docker + Kubernetes background I'm interested in writing easy ways to deploy stuff to Kubernetes.

I think it's too specific to build this kind of functionality directly into Meatier. But building it into Azk might make sense. What do you guys think?

**Comment by Bartekus** [comment]
I'm sorry for the delay @patrickleet , I got it almost done but I got just one more thing to figure out before it will be polished enough for everybody's use... 
Personally I'm all for dockerizing meatier, in fact we have started a side project as r3stack to eventually do just that but it's definitely the right direction @paralin so I'm more than happy to assist you and infact do encourage you to pursue this idea!

**Comment by patrickleet** [comment]
No worries about the delay, just wanted to help anyone who is trying to get things up and running ASAP before the next build is ready :)

**Comment by Bartekus** [comment]
alright, here is what we are working on, [r3stack](https://github.com/r3stack/r3stack) it still need the changes that you made applied to it, but it has the most completed deployment structure and all updates as well as we're trying to polish all aspects of it into it's own framework like architecture. Tho it's not really a framework, more like a crazy experiment to get kids onboard of developing cool things :)

**Comment by Bartekus** [comment]
fyi, I'm fairly sure webpack is cause of most of my problems at the moment, I downgraded from beta 2.0.7 to 2.0.6 to 2.0.5 to 2.0.4... so on back to 2.0.2 lol it doesn't like  
`compiler: {
    hash_type: 'hash',
    stats: {
      chunks: false,
      chunkModules: false,
      

> colors: true,

    },
  },`

lol, for now we'll use 2.0.2 and I'll talk to Kosta to find out why all of sudden colors we're taken out of the stats compiler. :/

**Comment by patrickleet** [comment]
Interesting.. why go to a new repository for what looks to be pretty much the same thing? I mean, it's really hard to tell as there is no diff.. Is this going to be merged back into Meatier? 

FWIW, the "meatier" name is clever, and communicates the goals pretty clearly. Also, I think the cheekiness draws people to it, especially as frustration with Meteor rises. This repo has gained 500 or so stars in the past week or so since I've found it, seems like if you want the most people using it as possible you'd stick with the repo that's already doing well?

**Comment by Bartekus** [comment]
That is true, but our alternative goal is not to live in meteors shadow but rather create alternative stack for hackers to train hackers... Meteor was commercial product, r3stack is by hackers for hackers, our gift to the anonymous movement if you will. And in that respect, the stars mean very little as it's the idea that it represents. Beside Meatier is perfect as it is and aside from gradual updates and changes it won't drastically morph into something else as it is in store for r3stack.

**Comment by Bartekus** [comment]
@patrickleet But your notion is duly noted... So I'll implement your changes immediately and integrate what I got so far working with r3stack into meatier so that a broader range of people can benefit from these improvements. Thank you for your objectivity and understanding.

**Comment by Bartekus** [comment]
As promissed your changes have been implemented and tested ok on the [Araphel](https://github.com/Araphel/meatier) branch

**Comment by Bartekus** [comment]
also [Meatier is now online](http://159.203.25.99/)

**Comment by paralin** [comment]
I'll start working towards some sort of deployment model targeting Kubernetes via Azk with Meatier as an example. Mostly because I want something like this for my own work.

**Comment by Bartekus** [comment]
Thats very cool, I honestly didn't know about Kubernetes so if you need any help, do let me know, I'm certainly interested in learning more about it!

**Comment by mattkrick** [comment]
@Bartekus the webpack problems are on me, the API is slightly in flux for v2 and I need to update the configs. See https://github.com/webpack/webpack/issues/1947 as Tobias explains exactly how to fix it

**Comment by Bartekus** [comment]
Ah that explains it, I was puzzled while looking at the docs but now it's much clearer. If you need any assistance do let me know, I'll be working on other dependencies as I've got update branch going also.

**Comment by Bartekus** [comment]
Let's keep this focused. 
This issue is resolved as of #95
I recommend closing this and reopening another ticket for webpack upgrade.

**Comment by wenzowski** [comment]
For the `git push` crowd there's also [dokku](https://github.com/dokku/dokku) and its [rethinkdb plugin](https://github.com/dokku/dokku-rethinkdb). All that takes is some `process.env.PORT` swapping and `NPM_CONFIG_PRODUCTION=false` for [cedarish](https://github.com/progrium/cedarish) to install webpack.

**Comment by ncrmro** [comment]
This isn't my exact config i'm using nor would I use it in prod without due diligence. I use tutum with a load balancer as it's much easier to configure and have image's automatically redeploy when triggered by a push to the docker hub image repo either from a manual push or from continuous integration (circle ci builds and pushs the docker image after a push to git, not much testing atm.)

 Still need either look more into database volume backup procedure or just use compose (the database service). 

* You will need the changes from the pull request #64


Create a local docker environment in virtual box and a remote. 
```
 docker-machine create -d virtualbox \
     --virtualbox-cpu-count "3" \
     --virtualbox-memory "4096" \
     default
```

`
docker-machine env default
`

```
  export DOCKER_TLS_VERIFY="1"
  export DOCKER_HOST="tcp://192.168.99.100:2376"
  export DOCKER_CERT_PATH="/Users/ncrmro/.docker/machine/machines/default"
  export DOCKER_MACHINE_NAME="default"
  # Run this command to configure your shell: 
  # eval $(docker-machine env default)
 ```


Build the docker image using this dockerfile
```
FROM node:5

# use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/

# From here we load our application's code in, therefore the previous docker
# "layer" thats been cached will be used if possible
WORKDIR /opt/app
ADD . /opt/app

RUN npm run build

ENV DATABASE_HOST=localhost \
    DATABASE_PORT=28015 \
    GRAPHQL_HOST=localhost \
    GRAPHQL_PROTOCOL=http

EXPOSE 3000

ENTRYPOINT ["npm"]

CMD ["run", "prod"]
```
 
 `docker build -t ncrmro/meatier:master .`

Push the image
 `docker login --username=yourhubusername --email=youremail@company.com`

`docker push ncrmro/meatier:develop`

Create a new prod docker machine.

```
docker-machine create --driver digitalocean \
     --digitalocean-access-token=abc123 \
     new-docker-machine-name
```
Change the docker environment to the new machine.

`
docker-machine env new-docker-machine-name
`

Docker-compose file consists of a base environment for development (Webpack Not refreshing correctly, something something rsync)

The database url

This will pull the rethinkdb and build your app. We want to over ride this in production eg.

docker-compose.yml
```
version: '2'

services:
  db:
    image: rethinkdb
    ports:
        - "8080:8080"
        - "28015"
        - "29015"
    volumes:
        - /data

  app:
    build: .
    volumes:
      - ./src/:/opt/app/src
    ports:
        - "80:3000"
    command: start
    environment:
      DATABASE_HOST: kaasol_db_1
      GRAPHQL_HOST: kaasol_app_1
      GRAPHQL_PROTOCOL: http
```
docker-compose.prod.yml
```
version: '2'

services:
  app:
    image: ncrmro/meatier:develop
```



`docker-compose -f docker-compose.yml -f docker-compose.prod.yml up`

**Comment by mattkrick** [comment]
Rather than create a new issue, let's just get all the options out there. azk.io seemed like the easiest, most straightforward, but I'd love to see all the options we have & compare ease of use & power of each.

**Comment by ncrmro** [comment]
Some one one gitter asked about how tutum is working.

Here is a circle.yml file that will build and run a docker image from a github repo. (no tests atm just makes sure everything starts up etc and builds the image, circle ci also has 4gb ram so builds happen decently fast)

Was hoping to pass the repo name and owner through the circle environment variables but atm docker itself won't take the the $ in the initial branch name tag.

Same issue with the two deployment branch configurations eg they don't register the $CIRCLE_BRANCH_NAME env or what ever.

The dockhub password, username and email is stored as an env variable from the circle ci website (hopefully get api key access soon.)


```
machine:
  environment:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build -t ncrmro/kaasol:$CIRCLE_BRANCH .

test:
  override:
    - docker run -d -p 8080:80 ncrmro/meatier:$CIRCLE_BRANCH

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ncrmro/meatier:master

deployment:
  hub:
    branch: develop
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ncrmro/meatier:develop
```

Now if you choose the docker-machine route you can use [watchtower](https://github.com/CenturyLinkLabs/watchtower) with your docker compose file to automatically check every few minutes and update the image if available (i've had problems with this atm because my docker image is a private repo.)

If you use a tutum, add the docker hub repo on their site. Set up the node-cluster (I used one machine atm 1gb ram single core on aws (aws free tier works great) or digital ocean. 

The node cluster should be tagged the project name and the development branch I have develop and master

Tutum stack-file below.
* Haproxy will automatically distribute request on port 80 or 443 to one of the meatier containers.
* The database environment variable is automatically redirected to the rethinkdb container. 

Once you set this up you'll need a redeploy trigger for the web container. Then you add this trigger url to your dockerhub so once new images are pushed it will trigger tutum to pull the latest image (ATM I think the redeploy trigger hit's isn't branch/tag specefic eg dockerhub will trigger the redeploy anytime a new image is pushed)

```
lb:
  image: 'tutum/haproxy:latest'
  links:
    - web
  ports:
    - '80:80'
  roles:
    - global
  tags:
    - develop
    - meatier
rethinkdb:
  image: 'rethinkdb:latest'
  ports:
    - '8080:8080'
  tags:
    - develop
    - meatier
web:
  image: 'ncrmro/meatier:develop'
  environment:
    - DATABASE_HOST=rethinkdb
    - GRAPHQL_HOST=dev.meatier.com
  links:
    - rethinkdb
  tags:
    - develop
    - meatier
```
